spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 20

session:
  cleanup:
    fixed-delay-ms: 900000
